package p2pfood;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class Forum
 */
@WebServlet("/p2plist")
public class P2PList extends HttpServlet {
	private static final long serialVersionUID = 1L;

	/**
	 * @see HttpServlet#HttpServlet()
	 */
	public P2PList() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		PrintWriter pw = response.getWriter();
		pw.append("<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Strict//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd'>"
+"<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='en' lang='en'>"
+"<head>"
+"<title>PotHub Bans</title>"
+"<meta http-equiv='content-language' content='en-us' />"
+"<meta http-equiv='content-type' content='text/html; charset=utf-8' />"
+"<link rel='stylesheet' type='text/css' media='screen' href='css/p2plist.css' />"
+"<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>"
+"<script src='//cdnjs.cloudflare.com/ajax/libs/tether/1.3.1/js/tether.min.js'></script>"
+"<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css' integrity='sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ' crossorigin='anonymous'>"
+"<script src='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js' integrity='sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn' crossorigin='anonymous'></script>"
+"<script src='https://use.fontawesome.com/aff6d7353c.js'></script>"
+"</head>"
+"<body id='babout'>"
+"<div id='header'>"
  +"<a href='adminpanel.html'>"
  +"<h1>Admin Panel</h1>"
+"</a>"
+"</div>"
+"<div id='navigation'>"
  +"<ul>"
    +"<li>"+"<a href='AdminGeneral'>General</a>"+"</li>"
    +"<li>"+"<a href='AdminBans'>Bans & Appeals</a>"+"</li>"
    +"<li>"+"<a href='AdminDonations'>Donation History</a>"+"</li>"
    +"<li>"+"<a href='AdminForumControl'>Forum Control</a>"+"</li>"
    +"<li>"+"<a href='AdminSupport'>Support Tickets</a>"+"</li>"
  +"</ul>"
+"</div>"
+"<div id='left-wrap'>"
  +"<img height=184 width =184 src='http://www.telegraph.co.uk/content/dam/news/2016/11/27/dump-tower-twitter_trans_NvBQzQNjv4BqeY8zn44CJx5co60z9sMGTUWjmulo7wva9c-kqRbE-Zc.jpg'>"
  +"<p>Having a good time at YOUR CURRENT ESTIMATED ADDRESS? Would food make it better?</p>"
  +"<p>Go get something to eat!</p>"
+"</div>"
+"<div id='trendythings'>"
+"<img height=360 width =360 src='http://www.telegraph.co.uk/content/dam/news/2016/11/27/dump-tower-twitter_trans_NvBQzQNjv4BqeY8zn44CJx5co60z9sMGTUWjmulo7wva9c-kqRbE-Zc.jpg'>"
+"<img height=360 width =360 src='http://www.telegraph.co.uk/content/dam/news/2016/11/27/dump-tower-twitter_trans_NvBQzQNjv4BqeY8zn44CJx5co60z9sMGTUWjmulo7wva9c-kqRbE-Zc.jpg'>"
+"<img height=360 width =360 src='http://www.telegraph.co.uk/content/dam/news/2016/11/27/dump-tower-twitter_trans_NvBQzQNjv4BqeY8zn44CJx5co60z9sMGTUWjmulo7wva9c-kqRbE-Zc.jpg'>"
+"<img height=360 width =360 src='http://www.telegraph.co.uk/content/dam/news/2016/11/27/dump-tower-twitter_trans_NvBQzQNjv4BqeY8zn44CJx5co60z9sMGTUWjmulo7wva9c-kqRbE-Zc.jpg'>"
+"</div>"
+"<div id='content'>"
+"<div id='displayUnit'>"
+"<img height=360 width =360 src='http://bk-apac-prd.s3.amazonaws.com/sites/burgerking.co.nz/files/BUR2423D_Kings-Collection_PRODUCT_500x400_02%5B1%5D.png'>"
+"<p id='foodtitle'>Homemade Burger</p>"
+"<p id='pickup'>5.40pm</p>"
+"</div>"
+"</div>"
+"<div id='wrapper'>"
+"<div class='container-fluid'>"
  	+"<div class='row'>"
	    +"<div class='col-sm-4 content'>"
			+"<div class='top-container'>"
				+"<div class='top-container-image-container'>"
					+"<div class='top-container-image'>"
						+"<img src='images/crab.jpg' alt='crab picture'>"
					+"</div>"
					+"<div class='top-container-image-gradient' onmouseenter='showOverlay(this)'>"
						+"<div class='event-title'>"
							+"<p>Tea Party</p>"
						+"</div>"
					+"</div>"
					+"<div class='overlay' onmouseleave='hideOverlay(this)'>"
						+"<div class='event-layout-title'>"
							+"<p>Tea Party</p>"
							+"<hr>"
						+"</div>"
						+"<div class='event-layout-desc'>"
							+"<p>Hosting a tea party at my house</p>"
						+"</div>"
						+"<div class='event-layout-location'>"
							+"<p><b>Location</b></p>"
							+"<p>'Singapore, Compass One'</p>"
						+"</div>"
						+"<div class='event-layout-guest'>"
							+"<div>"
								+"<p><b>Guest</b></p>"
							+"</div>"
							+"<div class='event-layout-guest-guest'>"
								+"<img src='images/cat.png' alt='cat picture' height='50' width='50'><br>"
								+"<p>Cat</p>"
							+"</div>"
							+"<div class='event-layout-guest-guest'>"
								+"<img src='images/crab.jpg' alt='crab picture' height='50' width='50'><br>"
								+"<p>Crab</p>"
							+"</div>"
						+"</div>"
					+"</div>"
				+"</div>"
				+"<div class='top-container-bottom'>"
					+"<div class='top-container-bottom-left'>"
						+"<p>Hosting a tea party at my house</p>"
					+"</div>"
					+"<div class='top-container-bottom-right'>"
						+"<p><i class='fa fa-users' aria-hidden='true'></i>13 Max</p>"
						+"<p><i class='fa fa-eye' aria-hidden='true'></i>38 Read</p>"
						+"<p><i class='fa fa-handshake-o' aria-hidden='true'></i>4 Joined</p>"
					+"</div>"
				+"</div>"
			+"</div>"
			+"<div class='bot-container'>"
				+"<div class='bot-container-image'>"
				+"<img src='images/cat.png' alt='cat picture'>"
				+"</div>"
				+"<div class='bot-container-name'>"
					+"<p>By <span style='font-weight:bold;color:green;'>Kitty</span></p>"
				+"</div>"
				+"<div class='bot-container-right'>"
				+"<p><i class='fa fa-heart-o fa-fw' aria-hidden='true'></i>23.7K Reputation</p>"
				+"<p><i class='fa fa-star-o fa-fw' aria-hidden='true'></i>Grandmaster</p>"
				+"</div>"
			+"</div>"
		+"</div>"
	    +"<div class='col-sm-4 content'>"
			+"<div class='top-container'>"
				+"<div class='top-container-image-container'>"
					+"<div class='top-container-image'>"
					+"<img src='images/crab.jpg' alt='crab picture'>"
					+"</div>"
					+"<div class='top-container-image-gradient' onmouseenter='showOverlay(this)'>"
						+"<div class='event-title'>"
							+"<p>Tea Party</p>"
						+"</div>"
					+"</div>"
					+"<div class='overlay' onmouseleave='hideOverlay(this)'>"
						+"<div class='event-layout-title'>"
							+"<p>Tea Party</p>"
							+"<hr>"
						+"</div>"
						+"<div class='event-layout-desc'>"
							+"<p>Hosting a tea party at my house</p>"
						+"</div>"
						+"<div class='event-layout-location'>"
							+"<p><b>Location</b></p>"
							+"<p>Singapore, Compass One</p>"
						+"</div>"
						+"<div class='event-layout-guest'>"
							+"<div>"
								+"<p><b>Guest</b></p>"
							+"</div>"
							+"<div class='event-layout-guest-guest'>"
							+"<img src='images/cat.png' alt='cat picture' height='50' width='50'><br>"
								+"<p>Cat</p>"
							+"</div>"
							+"<div class='event-layout-guest-guest'>"
							+"<img src='images/crab.jpg' alt='crab picture' height='50' width='50'><br>"
								+"<p>Crab</p>"
							+"</div>"
						+"</div>"
					+"</div>"
				+"</div>"
				+"<div class='top-container-bottom'>"
					+"<div class='top-container-bottom-left'>"
						+"<p>Hosting a tea party at my house</p>"
					+"</div>"
					+"<div class='top-container-bottom-right'>"
						+"<p><i class='fa fa-users' aria-hidden='true'></i>13 Max</p>"
						+"<p><i class='fa fa-eye' aria-hidden='true'></i>38 Read</p>"
						+"<p><i class='fa fa-handshake-o' aria-hidden='true'></i>4 Joined</p>"
					+"</div>"
				+"</div>"
			+"</div>"
			+"<div class='bot-container'>"
				+"<div class='bot-container-image'>"
				+"<img src='images/cat.png' alt='cat picture'>"
				+"</div>"
				+"<div class='bot-container-name'>"
					+"<p>By <span style='font-weight:bold;color:green;'>Kitty</span></p>"
				+"</div>"
				+"<div class='bot-container-right'>"
					+"<p><i class='fa fa-heart-o fa-fw' aria-hidden='true'></i>23.7K Reputation</p>"
					+"<p><i class='fa fa-star-o fa-fw' aria-hidden='true'></i>Grandmaster</p>"
				+"</div>"
			+"</div>"
		+"</div>"
	    +"<div class='col-sm-4 content'>"
			+"<div class='top-container'>"
				+"<div class='top-container-image-container'>"
					+"<div class='top-container-image'>"
					+"<img src='images/crab.jpg' alt='crab picture'>"
					+"</div>"
					+"<div class='top-container-image-gradient' onmouseenter='showOverlay(this)'>"
						+"<div class='event-title'>"
						+"<p>Tea Party</p>"
						+"</div>"
					+"</div>"
					+"<div class='overlay' onmouseleave='hideOverlay(this)'>"
						+"<div class='event-layout-title'>"
						+"<p>Tea Party</p>"
							+"<hr>"
						+"</div>"
						+"<div class='event-layout-desc'>"
						+"<p>Hosting a tea party at my house</p>"
						+"</div>"
						+"<div class='event-layout-location'>"
						+"<p><b>Location</b></p>"
						+"<p>Singapore, Compass One</p>"
						+"</div>"
						+"<div class='event-layout-guest'>"
							+"<div>"
							+"<p><b>Guest</b></p>"
							+"</div>"
							+"<div class='event-layout-guest-guest'>"
							+"<img src='images/cat.png' alt='cat picture' height='50' width='50'><br>"
							+"<p>Cat</p>"
							+"</div>"
							+"<div class='event-layout-guest-guest'>"
							+"<img src='images/crab.jpg' alt='crab picture' height='50' width='50'><br>"
							+"<p>Crab</p>"
							+"</div>"
						+"</div>"
					+"</div>"
				+"</div>"
				+"<div class='top-container-bottom'>"
					+"<div class='top-container-bottom-left'>"
					+"<p>Hosting a tea party at my house</p>"
					+"</div>"
					+"<div class='top-container-bottom-right'>"
					+"<p><i class='fa fa-users' aria-hidden='true'></i>13 Max</p>"
					+"<p><i class='fa fa-eye' aria-hidden='true'></i>38 Read</p>"
					+"<p><i class='fa fa-handshake-o' aria-hidden='true'></i>4 Joined</p>"
					+"</div>"
				+"</div>"
			+"</div>"
			+"<div class='bot-container'>"
				+"<div class='bot-container-image'>"
					+"<img src='images/cat.png' alt='cat picture'>"
				+"</div>"
				+"<div class='bot-container-name'>"
				+"<p>By <span style='font-weight:bold;color:green;'>Kitty</span></p>"
				+"</div>"
				+"<div class='bot-container-right'>"
				+"<p><i class='fa fa-heart-o fa-fw' aria-hidden='true'></i>23.7K Reputation</p>"
				+"<p><i class='fa fa-star-o fa-fw' aria-hidden='true'></i>Grandmaster</p>"
				+"</div>"
			+"</div>"
		+"</div>"
	+"</div>"
+"</div>"
+"</div>"
+"<div id='footer'>"
  +"<p>Copyright &copy; 2017 &ndash; 2018 PotHub. All rights reserved. </p>"
  +"<p>We like food</p>"
  +"<p>" +"<a href='#'>Terms of Service</a> | <a href='#'>Privacy</a> | <a href='#'>Support</a>"+"</p>"
+"</div>"
+"</body>"
+"</html>");
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse
	 *      response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}
